name: CI

on:
  push:
    tags:
      - "*"
    paths:
      - Package Managers.alfredworkflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Rename Alfred Workflow
        run: mv "Package Managers.alfredworkflow" Package.Managers.alfredworkflow

      - name: Create GitHub Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          args: ${{ github.ref }}

      - name: GitHub Upload Release Artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: Package.Managers.alfredworkflow
